#!/bin/sh


rm *.S20*
cp /seismo/REA/opera/2009/02/*.S20*02 .
cp /seismo/REA/opera/2009/03/*.S20*03 .
cp /seismo/REA/opera/2009/04/*.S20*04 .
cp /seismo/REA/opera/2009/05/*.S20*05 .
cp /seismo/REA/opera/2009/06/*.S20*06 .
cp /seismo/REA/opera/2009/07/*.S20*07 .
cp /seismo/REA/opera/2009/08/*.S20*08 .
cp /seismo/REA/opera/2009/09/*.S20*09 .

ls -1 *.S20* > sfiles
while read a
do
awk 'BEGIN{FS="\n";i=0;e=0}{ano=substr($1,2,5);est=substr($1,2,3); if(ano=="2009-") {anoo=substr($1,2,4);mes=substr($1,7,2); dia=substr($1,10,2)};if(est=="ACA"||est=="AGL"||est=="ARE"||est=="CAP"||est=="CAR"||est=="CHA"||est=="COC"||est=="CUC"||est=="DBB"||est=="EL4"||est=="GIL"||est=="GUA"||est=="HEL"||est=="JUR"||est=="LOL"||est=="MUL"||est=="NAN"||est=="NEC"||est=="PPI"||est=="PRI"||est=="RUS"||est=="SJN"||est=="SOL"||est=="SPD"||est=="TRI"||est=="UNG"){i++;estt[i]=est;fase[i]=substr($1,11,1);hh[i]=substr($1,19,2);mm[i]=substr($1,21,2);ss[i]=substr($1,24,2);ssd[i]=substr($1,27,2)}}END{print anoo,mes,dia;for(k=1;k<=i;k++){if(fase[k]=="S"||fase[k]=="P"){h[k]=hh[k]+mm[k]/60+ss[k]/3600+ssd[k]/360000;print estt[k],fase[k],hh[k],mm[k],ss[k],ssd[k]}}}' $a >$a"j"

awk '{if(NR==1) {print $1,$2,$3}if(NR==2) {est[1]=$1;fase[1]=$2;h[1]=$3;m[1]=$4;sg[1]=$5;csg[1]=$6;i=2} if(NR>2) {est[i]=$1;fase[i]=$2;h[i]=$3;m[i]=$4;sg[i]=$5;csg[i]=$6;j=1; s=1; if((est[i]=="DBB"||est[i]=="HEL"||est[i]=="SOL")&&fase[i]=="P"){print est[i]," P ",h[i]*3600+m[i]*60+sg[i]+csg[i]/100};while (j<=i && s==1) {if (est[i]==est[j]){s=0;Dt[j]=(h[i]-h[j])*3600+(m[i]-m[j])*60+(sg[i]-sg[j])+(csg[i]-csg[j])/100;if(Dt[j]<0){Dt[j]=-Dt[j]};ss[j]=h[i]*3600+m[i]*60+sg[i]+csg[i]/100;print est[j]," SP",Dt[j]}else{s=1;j++} if(j==i && s==1){i++;s=0}}} } ' $a"j" > prueba2

awk 'BEGIN{cp=0;}{if(NR==1){fecha=$1" "$2" "$3}else{est[NR-1]=$1;fase[NR-1]=$2;t[NR-1]=$3;if(fase[NR-1]=="P"){cp++;}}}END{print NR-1,cp,fecha;for(k=1;k<NR;k++) {print fase[k],est[k],t[k]}}' prueba2 >prueba3

sort prueba3 >prueba4

awk '{if(NR==1){print "SISMO",$3,$4,$5}else{print $2,$1,$3}}' prueba4 > $a"j2"
awk 'BEGIN{i=1}{ if($2=="P"){   a=$3; if(i==1){am=a}; if(a<=am){am=a} ;i++  } }END{print am}' $a"j2">$a"j3"
done < "sfiles"

rm prueba2 prueba3 prueba4 sfiles
cat *j3 > MOD
cat *j2 > DATL
cat *j  > tobs
rm *.S20*
awk 'BEGIN{print 1}{print 147,270,30,$1}END {print 5.13}' MOD>MODIL
#cp -f DATL MODIL ../
awk 'BEGIN{c=0; d=0} {if ($1=="SISMO") {c++}else{d++}} END{print "Numero de sismos: "c "\nNumero de picadas: "d}' TOBS
